Feat/input system
ECONO-UNION/union-mentoring-2-Unity pull request #1
Opened 2022-02-26 10:41 UTC by jiyullee

- Input System 수정
- EventManager 추가
- Mouse & Keyboard Controller 추가

2022-02-26 10:43 UTC, jiyullee commented on Econo Union/Assets/Scripts/Event/EventManager.cs
> +
Listener 인터페이스를 이용한 방법

2022-02-26 10:46 UTC, jiyullee commented on Econo Union/Assets/Scripts/Event/EventManager.cs
> +
Delegate를 이용한 방법

2022-02-26 12:54 UTC, JuicyPark requested changes
지난코드에서 코드가 완전히 대격변 되버려서 지난 리뷰에 대한 반영은 따로없는것 같군요
좀더 설계적인 부분은 내일 화상으로 얘기를 나눠보는것도 좋을것같습니다

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/CustomWindow/InputSystem/ControllerTypeSelector.cs
> +            PlayerPrefs.SetInt("ControllerType", index);
PlayerPrefs의 해당 키값을 세팅하는데 스트링타입을 그대로 하면 실수의 여지가 있을것 같습니다.
따로 상수를 두는게 어떨까요

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Event/EventManager.cs
> +                DestroyImmediate(this);
Destroy대신 DestroyImmediate를 사용한 이유가있나요?
둘의 차이를 혹시 알고 계신가요?

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Event/EventManager.cs
> +        public void RemoveRedundancies()
Redundancies
좀더 쉬운단어로 표현할수있지않을까요?

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Event/EventManager.cs
> +    public enum EVENT_TYPE
코딩스탠다드를 일치하게 사용하는게 좋을것같습니다

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/Controller.cs
> +        var pivot = 1 << keyBit;
혹시 변수에 var를 사용하는 기준같은게 있나요? 

개인적으로는 기본타입의 변수에는 var를 지양해서 사용하고 있습니다. IDE없이 코드만 확인했을때 헷갈릴만한 요소가 되기도하기때문에, 타입의 이름이 긴경우 var를 자주사용하곤합니다

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/InputManager.cs
> +        int index = PlayerPrefs.GetInt("ControllerType");
에디터로 받아온 "ControllerType"의 index 값을 가져오는것 같은데
새로운 enum 타입이 중간에 추가가 되면 코드가 안전할까? 라는 생각이 드네요

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/KeyboardController.cs
> +            EventManager.Instance.PostNotification(keyInfo.EVENT_TYPE, GameManager.Player, new object[] { h, v });
Press 방식의 키는 오직 방향키만 사용할수 없는걸까요?

레이져를 쏘는 캐릭터가 나온다면 어떻게 처리해야할까요?

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Player/PlayerAction.cs
> +    void Attack()
PlayerAction에서 모든 key 에대한 동작까지 모두 정의하고있어서 키가 늘어날때마다 PlayerAction 코드만 비대해지는것 같습니다 A라는사람이 이동을 만들고, B라는 사람이 공격을 만들면 충돌이 날것만 같네요

로직을 분리해보는건 어떨까요?

2022-02-26 12:54 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/KeyboardController.cs
> +            if (HasKeyBit(keyBit))
아래에서 Input.GetKeyUp(keyCode) 로 키가 입력중인지 체킹하는 부분이 있는데
이렇게 키index를 나눠서 해당 키인덱스가 눌렸는지 체크하는부분이 왜 필요한지 잘 안 와닿는것 같습니다

2022-02-26 13:11 UTC, jiyullee commented on Econo Union/Assets/Scripts/Event/EventManager.cs
> +                DestroyImmediate(this);
만약에 싱글톤 객체가 두 개 생기면 문제가 생길 수 있어 즉시 지워지도록 하려고 사용했어요.

2022-02-26 13:17 UTC, jiyullee commented on Econo Union/Assets/Scripts/InputSystem/Controller.cs
> +        var pivot = 1 << keyBit;
딱히 기준은 없었는데, 짧은 변수에는 var 사용을 줄이는게 좋을 거 같네요

2022-02-26 13:58 UTC, jiyullee commented on Econo Union/Assets/Scripts/InputSystem/KeyboardController.cs
> +            EventManager.Instance.PostNotification(keyInfo.EVENT_TYPE, GameManager.Player, new object[] { h, v });
MOVE가 아닌 키들은 else 구역에서 처리합니다

2022-02-26 14:00 UTC, jiyullee commented on Econo Union/Assets/Scripts/Player/PlayerAction.cs
> +    void Attack()
아직 거기까진 생각 안해봤네요

2022-02-26 14:13 UTC, jiyullee commented on Econo Union/Assets/Scripts/InputSystem/KeyboardController.cs
> +            if (HasKeyBit(keyBit))
여기에서는 중복이라 필요없네요.

2022-03-08 09:37 UTC, jiyullee commented
InputSystem의 UML 다이어그램입니다.
[주요 클래스]
- InputManager (Controller 관리)
- Controller (키/버튼 입력 상태 관리)
- InputMapper (입력 커맨드를 Player/UI에 연결)
- InputInfo (키/버튼 정보)
- AxisInput (이동 입력 정보)
![image](https://user-images.githubusercontent.com/48905902/157208945-b515697e-c1fa-4538-ab85-9cbce80ff24d.png)

2022-03-09 01:38 UTC, JuicyPark requested changes
개인적으로 사용하는 네임스페이스를 활용한 모듈화 방식 (개인적임 주의)
1. InputManager, InputMapper 은 상위모듈들은 애초에 Script 폴더에도 넣어놓지 않고 가장 상위폴더로 InputSystem 과 같이 폴더를 따로 빼놓고 거기서 작업함
2. 그 폴더 내에 있는 스크립트들은 Namespace.InputSystem이런식으로 명명을 해두고
3. 사용자 관점의 스크립트들은 Script폴더 내에서 InputSystem이라는 폴더를 만들어서 거기서 추가해서 using namespace를 이용해서 모듈화된 inputsystem을 가져와서 사용하는 방식을 사용하곤 합니다

2022-03-09 01:38 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/InputManager.cs
> +    public enum MoveType
무브타입을 왜 나눴을까요?

2022-03-09 01:38 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/InputManager.cs
> +
inputManager에서 모든 컨트롤러를 생성해주고있는것같은데
마우스나 조이스틱을 사용하지 않는 플랫폼에서도 이 코드가 동일하게 동작할것같습니다.

2022-03-09 01:38 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/InputManager.cs
> +    void FixedUpdate()
Update랑 FixedUpdate를 각각
Update => 일반버튼
FixedUpdate => 이동버튼
이렇게 나눠놓은것 같은데 기준이있는것인지?

2022-03-09 01:38 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/InputManager.cs
> +    public static InputMapper SelectMapper(CommandType commandType)
키가 하나 추가될때마다 InputManager가 계속 수정되는부분에 대해서는 어떻게 생각할까요?

2022-03-09 02:11 UTC, JuicyPark commented on Econo Union/Assets/Scripts/InputSystem/Controller/KeyboardController.cs
> +    public override void Update()
상위 모듈에서 처리할만한 일인데 override의 필요성을 잘 못느끼고있습니다

2022-03-09 02:23 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Player/PlayerAction.cs
> +public partial class PlayerAction : MonoBehaviour
컴포넌트를 분리하는건 파샬클래스보다 좋은 방법이 있을것 같습니다

2022-03-14 15:07 UTC, jiyullee commented
1. InputSystem 구조
InputSystem은 Controller에서 커맨드의 입력 상태를 판별하여 InputMapper의 이벤트 핸들러로 입력 정보를 전달한다.
InputMapper는 Player 혹은 UI 객체에게 각 커맨드에 맞는 동작을 실행하도록 한다.
[Controller -> InputMapper -> Player]

2. InputManager 클래스
InputManager는 플랫폼별로 Controller를 생성 후 각 Controller가 역할을 수행하도록 한다. 
  
3. InputInfo 클래스 
각 키/버튼이 가지고 있는 정보이다.
커맨드 유형과 키/버튼의 입력 상태를 알 수 있다.
하위 클래스로 KeyInfo, MouseInfo, JoystickInfo가 있으며 이들은 각각 다른 키코드 혹은 버튼 종류를 가지고 있다.

4. Controller 클래스
키(버튼)에 대한 InputInfo를 담은 딕셔너리(KeyTable/ButtonTable)에서 모든 키(버튼)을 관리한다.
하지만 Axis 이동 커맨드는 AxisInput을 담은 AxisTable에서 따로 관리한다.
OnCheckInput()에서 Axis / Move / 나머지 총 3분류로 커맨드를 구분하여 입력 상태를 확인한다.   
하위 클래스인 MouseController의 경우 클릭 시 mousePosition으로 이동하는 Move 커맨드를 수행할 수 있다.

5. InputMapper
InputMapper는 Player 혹은 UI가 커맨드별로 수행할 내용을 기술할 수 있다. 
InputMapper.EventHandler는 Controller가 전달하는 이벤트를 기술하고 있다. 키/버튼 입력 시작와 입력 중, 입력 종료에 해당하는 OnSendCommandInput 대리자와 
Axis 입력에 해당하는 OnAxisInput 대리자, 특정 위치로 이동하는 OnMoveInput 대리자가 있으며 각 대리자에 해당하는 핸들러를 가지고 있다.

2022-03-14 17:02 UTC, JuicyPark requested changes
### 아직 모듈화에 대해서 이해가 좀더 필요한것 같습니다😉

---

모듈화에 대해서 가장 간단하게 생각해보는건 다른 프로젝트에서 내가 만든 모듈이 필요하다 했을때 내가 보내줄수있는 코드뭉치라고 생각하면 좋습니다

지금같은경우 InputSystem을 누군가 요청한다고 하면
1. InputManager는 일단 반드시필요해서 보내줘야겠죠
2. InputManager는 KeyboardController, MouseController, JoystickController에 **결합**되어있으니 3개의 Controller에 대한 코드도 보내줘야할것같습니다 (Joystick이랑 Keyboard를 사용하지않아도 말이지요)
3. 그렇게되면 역시 각 Controller에 있는 KeyData, JoyStickData, MouseData에 대한 내용도 함께 담기겠군요
---

InputSystem이라는 **모듈사이드**와
InputSystem을 사용할 **사용자사이드**를 좀더 고려해보시길 바랍니다

잘 이해가 되셨다면 다음 풀리퀘에서는 모듈사이드 코드들에만 namespace를 넣고 사용자사이드에는 namespace를 사용하지 않거나, 아니면 따로 모듈사이드와 사용자사이드의 구조를 그림으로 그려서 올려주면 잘이해했는지 파악하기 쉬울것 같습니다.

설계에 정답이 있다고 생각하진 않습니다 기획의 명세만 있을뿐이지

[기획서]
1. InputSystem 은 오로지 사용자가 정한 Input에 대해서 눌렸는지 누르고있는지 뗏는지에 대한 정보만 전달해주면된다
2. A모바일팀과 B콘솔팀에서 모두 사용할수있었으면 좋겠다

이 두가지 조건만 충족되면 된다고 생각하면될것 같습니다

---

2022-03-14 17:02 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Module/InputSystem/AxisInput.cs
> +                return 0;
사소한거긴한데
if문 
-1 , 1, 0 
3개로 줄일 수 있지않을까요

2022-03-14 17:02 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Module/InputSystem/Controller/Controller.cs
> +
Controller라는 상위 모듈에서
하위 모듈인 KeyBoardController, JoyStickController, MouseController에서 사용할 프로퍼티들을 왜 들고있어야할까요?
protected Dictionary<KeyCode,InputInfo> KeyTable
protected Dictionary<int, InputInfo> ButtonTable

의존성이 역전되고있는것 같습니다

2022-03-14 17:02 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Module/InputSystem/Controller/Controller.cs
> +
Move라는 개념을 사용하지않는 게임에서는 불필요한 메소드일까요?

Controller는 지금 만들려고하는 InputSystem에서 꽤나 상위모듈인데 사용자가 Move라는 개념을 사용할지 안할지도 모르는 상황인데 정의해두는건 불필요하지않을까 생각되네요

2022-03-14 17:02 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Module/InputSystem/Mapper/InputMapper.EventHandler.cs
> +    public partial class InputMapper
파샬클래스를 쓴 이유가 있을까요? 정말 지극히 개인적인 생각이지만 파샬클래스라는 문법자체를 별로안좋아합니다 (하나의 클래스가 너무 많은 기능을 담당하는 슈퍼클래스로 만들겠다는 말이기도 하기때문에 그럼에도 반드시 필요한 경우라면 사용하겠지만, 지율님은 어떤 생각으로 파샬을 썻는지 궁금하군요)

2022-03-14 17:02 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Module/InputSystem/Mapper/InputMapper.EventHandler.cs
> +    public partial class InputMapper
지금과 같은 Mapper 구조에서 만약 스노우브라더스나 메탈슬러그같은 2인용 게임을 만드는 팀에서는 어떻게 사용해야할까요? 특정키를 누르면 동시에 동작하지않을까요?

2022-03-21 12:04 UTC, jiyullee commented
1. InputSystem 구조 변경
- 전: 
   - InputManager가 Controller를 생성 및 관리
   -  Controller에서 입력 상태 확인 후 InputMapper의 대리자 호출
   - 컨트롤러(키보드, 마우스, 조이스틱)별로 다른 Controller 클래스 사용
- 후
   - 컨트롤러를 통합하여 InputManager에서 모든 키에 대한 입력 상태 확인
   -  InputMapper를 모듈 사이드에서 제외


2. 모듈 사이드 목록
- InputManager
   - 게임에서 사용할 모든 키에 대한 입력 상태 확인하는 클래스. CommandType과 PlayerType을 통해 KeyState관리
- Key
   - 특정 키에 대한 정보를 담은 클래스. 
   - ControllerType, PlayerType, CommandType, KeyCode 정보를 담고 있다.
- InputData
   - Key 클래스의 리스트를 가진 ScriptableObject 클래스. 
   - 에디터에서 Key들을 관리한다.
- KeyState
   - 특정 KeyCode에 대해 입력 여부 변수를 가진 클래스. 
   - 입력 시작/ 입력 중/ 입력 종료로 구분
- AxisInput
   - Axis 정보를 확인하는 클래스.
- SystemTool
   - InputSystem에 필요한 Enum들을 모아놓은 클래스. 
   - InputSystemEditor로 사용자가 코드를 작성한다.
- InputSystemEditor
   - 유니티 에디터에서 PlayerType, ControllerType, CommandType을 관리하도록 작성된  Editor 클래스.

2022-03-21 13:12 UTC, JuicyPark approved these changes
모듈사이드와 사용자사이드가 어느정도 분리가 되가고있군요 좋습니다 머지하셔도될것같습니다 수고하셨습니다

2022-03-21 13:12 UTC, JuicyPark commented on Econo Union/Assets/InputSystem/SystemTool.cs
> +namespace Easy.InputSystem
자동생성 코드는 많이들 주석으로
// 이 스크립트는 InputSystem으로부터 자동으로 생성된 스크립트입니다.

이런식으로 명시를 해서 수정하지 못하도록 써두더라구요 참고하시길바랍니다

2022-03-22 09:46 UTC, merged