Feat/csv
ECONO-UNION/union-mentoring-2-Unity pull request #2
Opened 2022-03-08 14:40 UTC by jiyullee

CSV 파일로부터 데이터를 파싱하여 테이블화시키는 TableSystem 구현

[TableSystem 주요 클래스]
 - Table (데이터 테이블을 관리)
 - TableLoader(CSV 파일로부터 데이터 파싱)
 - SystemTool(파싱된 string 변수를 실제 사용될 타입으로 변환)
 - 실제 사용될 PlayerData와 같은 클래스들은 Table을 상속하여 사용된다.
 
![image](https://user-images.githubusercontent.com/48905902/157260124-e0ac071b-5598-4cda-b7e1-d2c60b25859b.png)

2022-03-09 02:09 UTC, JuicyPark requested changes

2022-03-09 02:09 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Data/PlayerData.cs
> +    public class PlayerData : Table<PlayerData, PlayerData.PlayerDataInstance>
PlayerData가 싱글톤으로 사용될 필요는없을것 같습니다. 관리자에서 PlayerData 인스턴스를 가져오는 방식은 어떨까요?

2022-03-09 02:09 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Data/PlayerData.cs
> +            public int Damage;
[현재코드]
기획자가 csv의 새로운타입인 string타입의 Name을 추가하게 되면
개발자가 기획자로부터 얘기를 듣고 해당 코드의 public string Name을 추가해줘야함
---------------------------------------------------------------------------------------------
[제안하고싶은점 필수아님 주의]
https://github.com/ECONO-UNION/union-mentoring-1-Unity/blob/main/Union/Assets/InputSystem/Editor/InputSystemEditor.cs
에서 public void CreateEnumClass(List<Key> inputButtons) 함수를 보면 스크립트 파일을 새로 생성해주는 부분임
이부분을 참고해서 기획자가 버튼하나 누르면 개발자가 귀찮게 데이터를 수정할 필요없이 자동으로 반영될수있도록 코드를 한번 생각해봐도 좋을것 같습니다

2022-04-13 19:43 UTC, jiyullee commented
[시스템 순서]
1. CSV 파일을 Resources/Data/ 에 생성한다.
2. 유니티 에디터 상단의 Custom Window -> Data -> CSV Setting 창에서 CSV 파일들로부터 Data 스크립트를 생성한다.
![image](https://user-images.githubusercontent.com/48905902/163252227-ff0465cd-77e5-498e-897f-d3d31a78a689.png)
3. 생성된 스크립트들을 임포트한다.
4. DataManager.Instance.GetTableData(int)를 통해 데이터를 읽을 수 있다.

[시스템 주요 사항]
1. IData
 - 네임스페이스 : Easy.Data
 - CSV 파일의 변수를 저장하는 클래스
 - Editor로부터 생성된 클래스들을 자식으로 한다.
 
3. DataManager<T>
  - 네임스페이스 : Easy.Data
 - 데이터를 저장하는 클래스이다.
 - T는 IData 자식 클래스이다.
 - DataManager<T>의 싱글톤 Instance를 최초 참조할 때 CSV로부터 파일을 읽어와 데이터를 저장한다.
 - GetTableData(int)를 통해 원하는 key값의 데이터를 읽을 수 있다.
 
5. CsvStream
 - 네임스페이스 : Easy.Data.IO
 - CSV 파일 입출력을 담당하는 클래스이다.
 
7. CsvSystemEditor
 - 네임스페이스 : Easy.Data.Editor
 - Editor에 의해 동작하는 클래스이다.
 - CSV 파일의 이름에 맞는 스크립트를 생성하고 클래스를 작성한다.

8. ClassCreator
 - 네임스페이스 : Easy.Data
 - 스크립트를 생성하고 클래스를 작성하는 클래스
 -  4번의 CsvSystemEditor에서 참조한다.

10. Data 클래스들
 - 네임스페이스 : Easy.Data
 - CSV 파일의 변수들을 저장한다.
 - 5번의 ClassCreator에 의해 생성된 클래스 
 - Data 디렉토리 내에 위치한다.
 - ex) PlayerData, EnemyData, GameData, SoundData 등

2022-04-13 19:53 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +            File.WriteAllText(path, stringBuilder.ToString());
파일 생성 시  File.Create()를 통해 파일을 사용 중인 상태에서 File.WriteAllText()를 호출하면 이미 사용 중인 상태이기 때문에 IOException이 발생합니다. 
그래서 중간에 file.Close()를 넣었는데요.

이러면 파일을 열고 닫고 여는 형태가 되는데, 이러면 안좋을 거 같다는 생각이 듭니다.
그래도 File.WriteAllText()는 string을 한번에 쓸 수 있기 때문에 사용했는데요.

file을 중간에 Close 하지 않고 Write 하려면 FileStream.Write 메소드를 사용해야 하는데, 
이 메소드는 Write(Byte[] array, int offset, int count)입니다. 
FileStream.Write에 비해 File.WriteAllText가 편리하여 이렇게 작성하였는데, 이 방법을 써도 괜찮은지 궁금하네요.

2022-04-15 02:20 UTC, JuicyPark requested changes
고생하셨습니다. 고민을 많이 한 흔적이 있군요 리뷰반영후 코멘트 주시면 Approve해드리겠습니다

(추가적으로 유니티 세팅이랑 씬관련해서 충돌나던데 그부분도 같이 수정바랍니다)

2022-04-15 02:20 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +    public class ClassCreator
ClassCreator는 에디터 내에서만 사용하는 코드여서 Eidtor폴더에 있어야할것 같은데 런타임 위치에 있는것 같습니다.

Q. Editor폴더에 넣으면 어떤점이 좋을까요?

2022-04-15 02:20 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +            File.WriteAllText(path, stringBuilder.ToString());
해당부분에서는 세가지 코멘트를 드리고 싶습니다

**1.** 에디터용 코드는 런타임코드에 비해 상대적으로 최적화에 신경을 조금더 덜써도 되긴한다고 생각하지만. 하지만 그럼에도 최적화를 할 수 있는 부분이 있다면 당연히 하는게 좋다고 생각합니다 👍

2022-04-15 02:20 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +            File.WriteAllText(path, stringBuilder.ToString());
**2.** File.Create(path)를 사용했기때문에 해당 path에 대한 새로운 참조는 익셉션이 나는게 당연한것 같습니다. 이렇게 해보는건 어떨까요? 
```
if (!Directory.Exists(directoryPath))
    Directory.CreateDirectory(directoryPath);
```
파일이 있는지 없는지를 체크하는게 아니라 해당 디렉토리가 있는지 없는지 체크하고 디렉토리 생성만 한뒤 파일생성은 File.WriteAllText를 이용하는 방법입니다
![image](https://user-images.githubusercontent.com/31693348/163505780-2fe8a6fc-cd6f-40e5-8c43-c33b32c3e038.png)
File.WriteAllText는 파일이 없는 경우 생성해주고 있는경우에는 덮어쓰도록 됩니다

2022-04-15 02:20 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +            File.WriteAllText(path, stringBuilder.ToString());
**3.** 만약 기존에 만들어둔 코드가 성능적으로 비효율적이라 생각이 되었다면 실제로 그랬는지 1000개나 10000개의 파일을 열고 닫는 테스트에 시간을 체크하는 코드를 넣어서 얼마나 비효율적이었고 수정해서 몇초나 개선되었는지 체크해보는것도 좋을것 같습니다.

2022-04-15 02:20 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +        }
CreateClass로 코드를 완성하고나서 AssetDatabase.Refresh(); 를 추가해보는건 어떨까요?
추가한다고하면 왜 추가해야할까요?

2022-04-15 02:20 UTC, JuicyPark commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +                stringBuilder.AppendLine($"        public {fieldTypes[i]} {fieldnames[i]} {{ get; set; }}");
public get; set;보다는 public get; private set; 은 어떨까요?
csv data는 런타임에서 값을 수정해서는 안되는 값일것 같습니다

DataManager에서 리플렉션으로 넣어주기 때문에 private set을 사용해도 작동될것 같긴합니다

2022-04-15 20:11 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +    public class ClassCreator
넣을까 말까 고민했었는데요. ClassCreator는 Editor에서 직접 동작하지 않는 클래스라 넣지 않았어요.
하지만 Editor에서만 사용하기 때문에 Editor폴더에 넣으면 한눈에 보기 편하고 관리하기 쉽다는 장점이 있다고 생각합니다.

그렇지만 Editor 폴더 내에서는 ClassCreator가 EditorWindow를 상속받아 Editor를 동작하는지 안 하는지 잠깐 혼란을 줄 수 있기 때문에 넣는게 맞는지 안 맞는지 정답은 모르겠네요.

2022-04-15 20:14 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +    public class ClassCreator
Editor 폴더 내에서 EditorWindow 관련 스크립트만 넣어야 한다는 암묵적인 룰이 있을까요??
아니면 사소한 점이라 상관 없을려나요?

2022-04-15 20:26 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +            File.WriteAllText(path, stringBuilder.ToString());
좋은 피드백 감사합니다.
파일 1000개로 체크해봤더니
1. Create -> Close -> WriteAllText 과정이 400~500ms 걸리고
2. WriteAllText만 사용하는 방법과 Create -> Write -> Close의 경우에는 둘 다 220~240ms 정도로 비슷하게 걸리네요.

현재 작성된 코드는 파일을 여는 과정이 두 번이나 들어가 있네요.
준수님이 제안한 디렉토리 체크 후 WriteAllText만 사용하는 방법이 제일 베스트 같네요!

2022-04-15 20:28 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +            File.WriteAllText(path, stringBuilder.ToString());
최적화 부분에서 직접 시간 체크하면서 테스트 해보는 방법, 깨달아 갑니다

2022-04-15 20:32 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +        }
파일 생성 후 직접 새로고침 하고 임포트 해야해서 불편하다고 생각했는데, AssetDatabase.Refresh() 넣으니 자동으로 임포트 되니 편하네요!

2022-04-17 12:11 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +    public class ClassCreator
특수 폴더 -> 빌드 했을 때 영향을 주지 않는다.

2022-04-17 12:14 UTC, jiyullee commented on Econo Union/Assets/Scripts/Csv/ClassCreator.cs
> +        }
Editor 폴더 안, 네임스페이스 Editor 사용 할 때만 사용

2022-04-17 12:45 UTC, merged